/**
 * VIRGO Financial Dashboard - Overview Page
 * 
 * This is a Next.js Server Component that fetches financial data from Supabase
 * and displays key metrics, charts, and recent transactions.
 * 
 * Features:
 * - Fetches latest KPIs from v_kpis view
 * - Displays 4 metric cards with month-over-month comparison
 * - Shows revenue vs expenses line chart (6 months)
 * - Shows cash flow breakdown bar chart (3 months)
 * - Shows expense distribution donut chart
 * - Lists recent transactions in a table
 * - Displays last sync timestamp from qbo_connections
 * - Handles error states gracefully
 * 
 * Requirements: 10.1, 10.6, 10.1.1-10.1.12
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase/database.types';
import { format } from 'date-fns';
import OverviewClient from './OverviewClient';

// Type definitions for database views (not auto-generated by Supabase CLI)
type VKpisRow = {
  company_id: string;
  period_start: string;
  period_end: string;
  revenue: number | null;
  cogs: number | null;
  opex: number | null;
  gross_profit: number | null;
  gross_margin_pct: number | null;
  net_income: number | null;
  net_margin_pct: number | null;
  operating_cash_flow: number | null;
  investing_cash_flow: number | null;
  financing_cash_flow: number | null;
  row_version: number | null;
  generated_at: string | null;
  source_run_id: string | null;
  transaction_ids: any | null;
};

type VMonthlyPlRow = {
  row_id: string;
  company_id: string;
  start_date: string;
  end_date: string;
  revenue: number | null;
  cogs: number | null;
  opex: number | null;
  gross_profit: number | null;
  net_income: number | null;
  row_version: number | null;
  generated_at: string | null;
  source_run_id: string | null;
  transaction_ids: any | null;
};

type VMonthlyCashFlowRow = {
  row_id: string;
  company_id: string;
  start_date: string;
  end_date: string;
  operating_cash_flow: number | null;
  investing_cash_flow: number | null;
  financing_cash_flow: number | null;
  net_cash_flow: number | null;
  row_version: number | null;
  generated_at: string | null;
  source_run_id: string | null;
  transaction_ids: any | null;
};

// Server component - fetches data from Supabase
export default async function Home() {
  // Initialize Supabase client for server-side
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Configuration Error</h2>
          <p className="text-gray-600">
            Missing Supabase configuration. Please check your environment variables.
          </p>
        </div>
      </div>
    );
  }

  const supabase = createClient<Database>(supabaseUrl, supabaseKey);

  try {
    // Get the first company (for MVP - in production, this would be based on authenticated user)
    const { data: companies, error: companiesError } = await supabase
      .from('companies')
      .select('id, name')
      .limit(1)
      .single();

    if (companiesError || !companies) {
      return (
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-center">
            <h2 className="text-xl font-semibold text-gray-900 mb-2">No Company Found</h2>
            <p className="text-gray-600">
              No company data available. Please set up a company and sync QBO data first.
            </p>
          </div>
        </div>
      );
    }

    const companyId = companies.id;

    // Fetch latest KPIs from v_kpis view
    const { data: kpisData, error: kpisError } = await supabase
      .from('v_kpis' as any)
      .select('*')
      .eq('company_id', companyId)
      .order('period_start', { ascending: false })
      .limit(2) as { data: VKpisRow[] | null; error: any }; // Get current and previous month for comparison

    // Fetch last sync timestamp from qbo_connections
    const { data: connectionData } = await supabase
      .from('qbo_connections')
      .select('last_sync_at')
      .eq('company_id', companyId)
      .single();

    // Fetch monthly P&L data for charts (last 6 months)
    const { data: plData } = await supabase
      .from('v_monthly_pl' as any)
      .select('*')
      .eq('company_id', companyId)
      .order('start_date', { ascending: false })
      .limit(6) as { data: VMonthlyPlRow[] | null };

    // Fetch monthly cash flow data for charts (last 3 months)
    const { data: cashFlowData } = await supabase
      .from('v_monthly_cash_flow' as any)
      .select('*')
      .eq('company_id', companyId)
      .order('start_date', { ascending: false })
      .limit(3) as { data: VMonthlyCashFlowRow[] | null };

    // Fetch recent transactions (last 10)
    const { data: transactionsData } = await supabase
      .from('raw_transactions')
      .select('id, date, qbo_txn_id, txn_type, amount, currency, account_id, accounts(name)')
      .eq('company_id', companyId)
      .order('date', { ascending: false })
      .limit(10);

    // Calculate metrics with comparison to previous period
    const currentKPI = kpisData?.[0];
    const previousKPI = kpisData?.[1];

    const calculateChange = (current: number | null, previous: number | null): number => {
      if (!current || !previous || previous === 0) return 0;
      return ((current - previous) / Math.abs(previous)) * 100;
    };

    const formatCurrency = (value: number | null): string => {
      if (value === null || value === undefined) return '$0';
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0,
      }).format(value);
    };

    const formatPercent = (value: number | null): string => {
      if (value === null || value === undefined) return '0%';
      return `${value.toFixed(1)}%`;
    };

    // Prepare metrics data
    const metrics = {
      revenue: {
        value: formatCurrency(currentKPI?.revenue || 0),
        change: calculateChange(currentKPI?.revenue || 0, previousKPI?.revenue || 0),
      },
      netIncome: {
        value: formatCurrency(currentKPI?.net_income || 0),
        change: calculateChange(currentKPI?.net_income || 0, previousKPI?.net_income || 0),
      },
      opex: {
        value: formatCurrency(currentKPI?.opex || 0),
        change: calculateChange(currentKPI?.opex || 0, previousKPI?.opex || 0),
      },
      grossMargin: {
        value: formatPercent(currentKPI?.gross_margin_pct || 0),
        change: (currentKPI?.gross_margin_pct || 0) - (previousKPI?.gross_margin_pct || 0),
      },
    };

    // Prepare chart data - reverse to show oldest to newest
    const lineChartData = (plData || [])
      .reverse()
      .map((row) => ({
        month: format(new Date(row.start_date || ''), 'MMM'),
        revenue: Number(row.revenue) || 0,
        expenses: (Number(row.cogs) || 0) + (Number(row.opex) || 0),
      }));

    const barChartData = (cashFlowData || [])
      .reverse()
      .map((row) => ({
        month: format(new Date(row.start_date || ''), 'MMM'),
        operating: Number(row.operating_cash_flow) || 0,
        investing: Number(row.investing_cash_flow) || 0,
        financing: Number(row.financing_cash_flow) || 0,
      }));

    // Prepare donut chart data from latest KPI
    const donutChartData = [
      { name: 'Revenue', value: Math.abs(Number(currentKPI?.revenue) || 0) },
      { name: 'COGS', value: Math.abs(Number(currentKPI?.cogs) || 0) },
      { name: 'OpEx', value: Math.abs(Number(currentKPI?.opex) || 0) },
    ];

    // Prepare transactions table data
    const tableData = (transactionsData || []).map((txn) => ({
      date: format(new Date(txn.date), 'yyyy-MM-dd'),
      description: txn.txn_type,
      amount: formatCurrency(txn.amount),
      category: (txn.accounts as any)?.name || 'Unknown',
    }));

    // Pass data to client component
    return (
      <OverviewClient
        companyName={companies.name}
        lastSyncAt={connectionData?.last_sync_at || null}
        metrics={metrics}
        lineChartData={lineChartData}
        barChartData={barChartData}
        donutChartData={donutChartData}
        tableData={tableData}
        kpiMetrics={{
          grossMargin: formatPercent(currentKPI?.gross_margin_pct || 0),
          netMargin: formatPercent(currentKPI?.net_margin_pct || 0),
          operatingCashFlow: formatCurrency(currentKPI?.operating_cash_flow || 0),
          revenueGrowth: formatPercent(calculateChange(currentKPI?.revenue || 0, previousKPI?.revenue || 0)),
        }}
      />
    );
  } catch (error) {
    console.error('Error fetching dashboard data:', error);
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Error Loading Data</h2>
          <p className="text-gray-600">
            There was an error loading the dashboard data. Please try again later.
          </p>
          {error instanceof Error && (
            <p className="text-sm text-gray-500 mt-2">{error.message}</p>
          )}
        </div>
      </div>
    );
  }
}
